name: reichan kawaii
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  workflow_dispatch:
jobs:
  reichan-kawaii:
    runs-on: ubuntu-22.04
    steps:
      - name: Notice slack
        run: |
          image_url=$(curl -L ${{ secrets.REICHAN_KAWAII_URL }})
          curl -X POST -H 'Content-type: application/json' --data '{"text":"", "attachments" : [{"image_url": "${image_url}"}]}' ${{ secrets.SLACK_WEBHOOK_URL }}
