name: reichan kawaii
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  workflow_dispatch:
jobs:
  reichan-kawaii:
    runs-on: ubuntu-22.04
    steps:
      - name: Reichan kawaii
        run: |
          body='{"text":"$(curl -L ${{ secrets.REICHAN_KAWAII_URL }})"}'
          echo ${body}
          curl -X POST -H 'Content-type: application/json' --data ${body} ${{ secrets.SLACK_WEBHOOK_URL }}
